name: SoulChange
version: ${version}
main: com.github.kdy05.soulChange.SoulChange
depend: [ "SkinsRestorer" ]
api-version: '1.21'
commands:
  soulchange:
    description: Plugin's Main Command
    aliases: [sc]
permissions:
  soulchange.use:
    description: Allows using the basic commands
    default: op
  soulchange.reload:
    description: Allows reloading configurations
    default: op