name: SoulChange
version: ${version}
main: com.github.kdy05.soulChange.SoulChange
depend: [DisguiseAPI]
api-version: '1.21'
commands:
  soulchange:
    description: Plugin's Main Command
    aliases: [sc]
